export interface Product {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  ageRange: { min: number; max: number };
  price: number;
  inventory: number;
  category: string;
}

export const products: Product[] = [
  {
    id: "toy-001",
    name: "Rainbow Stacking Rings",
    description: "Colorful wooden stacking rings that help develop hand-eye coordination and color recognition. Features 8 vibrant rings in graduated sizes.",
    keywords: ["stacking", "wooden", "colors", "motor skills", "rings"],
    ageRange: { min: 0, max: 2 },
    price: 14.99,
    inventory: 45,
    category: "developmental",
  },
  {
    id: "toy-002",
    name: "Soft Plush Elephant",
    description: "Ultra-soft cuddly elephant plush toy with crinkle ears and a squeaker. Machine washable and made with baby-safe materials.",
    keywords: ["plush", "stuffed animal", "elephant", "soft", "cuddly"],
    ageRange: { min: 0, max: 3 },
    price: 19.99,
    inventory: 62,
    category: "plush",
  },
  {
    id: "toy-003",
    name: "Musical Activity Cube",
    description: "Five-sided activity cube with spinning gears, bead maze, shape sorter, xylophone, and peek-a-boo doors. Encourages exploration and discovery.",
    keywords: ["activity", "music", "cube", "shapes", "gears", "interactive"],
    ageRange: { min: 1, max: 3 },
    price: 34.99,
    inventory: 28,
    category: "developmental",
  },
  {
    id: "toy-004",
    name: "Mega Block Builder Set (80 pieces)",
    description: "Large, chunky building blocks perfect for small hands. Includes 80 colorful interlocking pieces in a storage bag. Compatible with major brands.",
    keywords: ["blocks", "building", "construction", "creative", "mega"],
    ageRange: { min: 1, max: 5 },
    price: 24.99,
    inventory: 55,
    category: "building",
  },
  {
    id: "toy-005",
    name: "Wooden Train Set",
    description: "32-piece wooden train set with tracks, bridges, trees, and two magnetic trains. Compatible with all major wooden railway systems.",
    keywords: ["train", "wooden", "tracks", "railroad", "vehicles"],
    ageRange: { min: 2, max: 6 },
    price: 39.99,
    inventory: 33,
    category: "vehicles",
  },
  {
    id: "toy-006",
    name: "Play-Doh Mega Pack (24 colors)",
    description: "24 cans of classic Play-Doh in a rainbow of colors. Non-toxic modeling compound that sparks creativity and imagination.",
    keywords: ["playdoh", "clay", "modeling", "creative", "art", "colors"],
    ageRange: { min: 2, max: 8 },
    price: 18.99,
    inventory: 70,
    category: "arts-crafts",
  },
  {
    id: "toy-007",
    name: "Dinosaur Explorer Kit",
    description: "12 realistic dinosaur figurines with a fold-out prehistoric playmat. Includes a field guide booklet with fun dinosaur facts.",
    keywords: ["dinosaur", "figurines", "prehistoric", "educational", "science"],
    ageRange: { min: 3, max: 8 },
    price: 27.99,
    inventory: 41,
    category: "figurines",
  },
  {
    id: "toy-008",
    name: "Princess Castle Playset",
    description: "Enchanted castle playset with two princess dolls, a unicorn, furniture, and magical accessories. Castle opens to reveal three floors of play space.",
    keywords: ["castle", "princess", "dolls", "fantasy", "pretend play"],
    ageRange: { min: 3, max: 7 },
    price: 44.99,
    inventory: 22,
    category: "pretend-play",
  },
  {
    id: "toy-009",
    name: "Junior Scrabble",
    description: "Kid-friendly version of the classic word game with two difficulty levels. Features colorful tiles, a two-sided game board, and picture clues for beginners.",
    keywords: ["scrabble", "word game", "letters", "spelling", "educational"],
    ageRange: { min: 4, max: 8 },
    price: 21.99,
    inventory: 38,
    category: "board-games",
  },
  {
    id: "toy-010",
    name: "Remote Control Racing Car",
    description: "Sleek RC racing car with 2.4GHz remote control for interference-free racing. Reaches speeds up to 15mph with responsive steering.",
    keywords: ["RC", "remote control", "car", "racing", "vehicle", "speed"],
    ageRange: { min: 5, max: 12 },
    price: 32.99,
    inventory: 29,
    category: "vehicles",
  },
  {
    id: "toy-011",
    name: "Science Lab Chemistry Set",
    description: "Safe and exciting chemistry set with 50+ experiments. Includes test tubes, goggles, and all chemicals needed. Real science for curious minds.",
    keywords: ["science", "chemistry", "experiments", "STEM", "lab", "educational"],
    ageRange: { min: 6, max: 12 },
    price: 36.99,
    inventory: 25,
    category: "stem",
  },
  {
    id: "toy-012",
    name: "1000-Piece Space Puzzle",
    description: "Stunning 1000-piece jigsaw puzzle featuring a detailed illustration of our solar system. Finished size is 27x20 inches.",
    keywords: ["puzzle", "jigsaw", "space", "planets", "solar system"],
    ageRange: { min: 8, max: 14 },
    price: 16.99,
    inventory: 50,
    category: "puzzles",
  },
  {
    id: "toy-013",
    name: "LEGO-Compatible Robot Builder (450 pieces)",
    description: "Build your own motorized robot with this 450-piece construction set. Includes motor, LED lights, and step-by-step instructions for 3 different robot designs.",
    keywords: ["robot", "building", "construction", "STEM", "motor", "LED"],
    ageRange: { min: 7, max: 14 },
    price: 49.99,
    inventory: 18,
    category: "building",
  },
  {
    id: "toy-014",
    name: "Magic Trick Master Kit",
    description: "Professional-quality magic set with 75 tricks including card tricks, disappearing acts, and illusions. Includes instructional DVD and secret compartment props.",
    keywords: ["magic", "tricks", "illusion", "performance", "cards"],
    ageRange: { min: 6, max: 12 },
    price: 29.99,
    inventory: 35,
    category: "performance",
  },
  {
    id: "toy-015",
    name: "Watercolor Painting Kit",
    description: "Complete watercolor set with 36 colors, 3 brushes, mixing palette, and a pad of watercolor paper. Perfect for budding artists.",
    keywords: ["art", "painting", "watercolor", "creative", "brushes"],
    ageRange: { min: 5, max: 12 },
    price: 22.99,
    inventory: 42,
    category: "arts-crafts",
  },
  {
    id: "toy-016",
    name: "Outdoor Explorer Binoculars",
    description: "Kid-tough binoculars with 8x magnification, rubber-coated body, and neck strap. Comes with a bird-watching guide and nature journal.",
    keywords: ["binoculars", "nature", "outdoor", "birds", "exploration"],
    ageRange: { min: 4, max: 10 },
    price: 26.99,
    inventory: 30,
    category: "outdoor",
  },
  {
    id: "toy-017",
    name: "Coding Robot Buddy",
    description: "Programmable robot that teaches coding basics through play. Use the included coding cards or the free app to program dance moves, sounds, and light shows.",
    keywords: ["coding", "programming", "robot", "STEM", "technology", "app"],
    ageRange: { min: 5, max: 10 },
    price: 59.99,
    inventory: 15,
    category: "stem",
  },
  {
    id: "toy-018",
    name: "Marble Run Deluxe (120 pieces)",
    description: "Build incredible marble runs with 120 translucent pieces including funnels, spinners, and chutes. Includes 30 glass marbles.",
    keywords: ["marble", "run", "building", "gravity", "construction"],
    ageRange: { min: 4, max: 10 },
    price: 38.99,
    inventory: 24,
    category: "building",
  },
  {
    id: "toy-019",
    name: "Fashion Design Studio",
    description: "Design and create real fabric fashions with this complete studio set. Includes mannequin, fabric, pins, stencils, and a sketchbook.",
    keywords: ["fashion", "design", "sewing", "creative", "fabric", "art"],
    ageRange: { min: 8, max: 14 },
    price: 34.99,
    inventory: 20,
    category: "arts-crafts",
  },
  {
    id: "toy-020",
    name: "Strategy Board Game: Castle Siege",
    description: "Epic medieval strategy game where players build castles, train armies, and compete for the kingdom. For 2-4 players, games last 30-45 minutes.",
    keywords: ["strategy", "board game", "medieval", "castle", "multiplayer"],
    ageRange: { min: 8, max: 14 },
    price: 31.99,
    inventory: 27,
    category: "board-games",
  },
  {
    id: "toy-021",
    name: "Baby's First Books (Set of 6)",
    description: "Soft fabric books with crinkle pages, bright patterns, and teething-safe corners. Topics include animals, colors, numbers, shapes, food, and vehicles.",
    keywords: ["books", "baby", "fabric", "soft", "learning", "reading"],
    ageRange: { min: 0, max: 2 },
    price: 24.99,
    inventory: 55,
    category: "developmental",
  },
  {
    id: "toy-022",
    name: "Kick Scooter Pro",
    description: "Adjustable-height kick scooter with light-up wheels and a wide deck. Folds flat for easy storage. Supports up to 110 lbs.",
    keywords: ["scooter", "outdoor", "wheels", "riding", "active"],
    ageRange: { min: 5, max: 12 },
    price: 54.99,
    inventory: 19,
    category: "outdoor",
  },
  {
    id: "toy-023",
    name: "Spy Gear Detective Kit",
    description: "Top-secret spy kit with night vision scope, fingerprint kit, invisible ink pen, walkie-talkies, and a decoder ring.",
    keywords: ["spy", "detective", "secret", "walkie-talkie", "investigation"],
    ageRange: { min: 6, max: 12 },
    price: 42.99,
    inventory: 23,
    category: "pretend-play",
  },
  {
    id: "toy-024",
    name: "Kinetic Sand Deluxe Set",
    description: "4 lbs of magical kinetic sand in 6 colors with molds, tools, and a sand tray. Mess-free sensory play that never dries out.",
    keywords: ["kinetic sand", "sensory", "molding", "sand", "tactile"],
    ageRange: { min: 3, max: 8 },
    price: 28.99,
    inventory: 40,
    category: "arts-crafts",
  },
  {
    id: "toy-025",
    name: "Telescope Starter Kit",
    description: "70mm refractor telescope with tripod, 2 eyepieces, and a star map. See the moon's craters and Saturn's rings from your backyard.",
    keywords: ["telescope", "astronomy", "stars", "space", "science", "STEM"],
    ageRange: { min: 8, max: 14 },
    price: 69.99,
    inventory: 12,
    category: "stem",
  },
];
